### ISSUE TITLE
Invalid signature: Expected HMAC SHA256 hex digest

### ISSUE THREAD

**Issue by muratcelebiler** [pusher/pusher-http-php#170]
Hi. I created presence channel but ı have signature problem on pusher.com. I created private channel I have no problem.

> Invalid signature: Expected HMAC SHA256 hex digest of 6838.12741855:presence-chat:{"user_id":1453,"user_info":{"name":"joe"}}, but got 

> js file 

    var APP_KEY                  = 'xxx';
    var CHANNEL_NAME    = 'presence-chat'; 

     // Open a connection to Channels
    var pusher = new Pusher(APP_KEY, {
      cluster: 'ap1',
      authEndpoint: '/presence_auth.php'
    });
    
    // Subscribe to a channel
    var presenceChannel = pusher.subscribe(CHANNEL_NAME);

    // Listen for events on your channel
    presenceChannel.bind('yeni-mesaj', function(message) {
        console.log(message);
    });

> config.php

    require __DIR__ . '/vendor/autoload.php';

    $app_id             = 'xx';
    $app_key          = 'xx';
    $app_secret      = 'xx';
    $app_cluster     = 'ap1';
    $channel           = 'presence-chat';
    $event              = 'yeni-mesaj';
    $socket_id        = '123.123';

    $pusher = new Pusher\Pusher($app_key, $app_secret, $app_id, array('cluster' => $app_cluster));

> presence_auth.php

    header('Content-Type: application/json');
    require 'config.php';
    echo $pusher->presence_auth($channel, $socket_id, 1453, array('name' => 'joe'));

**Comment by WillSewell** [comment]
The problem is you should not be hard coding the value of the channel name or socket ID in the server. You should be taking whatever channel name and socket ID are provided in the request to `presence_auth.php`, and pass them to the `presence_auth` function. You can get these request parameters via `$_POST['channel_name']` and `$_POST['socket_id']`.

Since this is not a bug with the library, you should [bring this up with our support team](https://support.pusher.com/hc/en-us) if you are still struggling.
