### ISSUE TITLE
user_info supplied to presence subscription is invalid

### ISSUE THREAD

**Issue by mottihoresh** [pusher/pusher-http-php#32]
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"user_info supplied to presence subscription is invalid - if supplied it must be a type of hash"}}}

What type of hash does the library expect?

**Comment by mottihoresh** [comment]
When passing in an array as the fourth parameter, it seems to work. Might be worth updating the docs for it.

**Comment by zimbatm** [comment]
Hi @mottihoresh what kind of argument where you passing before ?

**Comment by mottihoresh** [comment]
I was trying to supply it with a string

**Comment by zimbatm** [comment]
Not really sure how to follow-up on this one. The error messages might have been easier to understand if it was checked in the PHP lib directly.

**Comment by leggetter** [comment]
Closing since there hasn't been any activity on this one for months.

**Comment by digitop** [comment]
I have the same error message, using Laravel 5.4, Pusher and Laravel Echo. The problem was in the routes/channels.php file, when you are using PresenceChannels in the channel route's closure you must return with an user array. Read more: [Laravel PresenceChannel Doc](https://laravel.com/docs/5.4/broadcasting#presence-channels)

Here's my corrected code snippet:
```
Broadcast::channel('notifications.{userId}', function ($user, $userId) {
    if ($user->id == $userId)
        return ['id' => $user->id, 'name' => $user->name]; // Return the user array not true/false if user can access to channel
});
```
