### ISSUE TITLE
Drop PHP 5.3 and 5.4 Support

### ISSUE THREAD

**Issue by vinkla** [pusher/pusher-http-php#86]
IMO we should drop PHP 5.3 and 5.4 support and go with 5.5.9 as the minimum requirement. PHP 5.4 isn't supported anymore, it wont receive any security fixes as of september 2015.

**Comment by zimbatm** [comment]
I'm a bit reluctant to bump the minimum requirement because people never update their PHP. I don't think that it's our role to force people to upgrade to use Pusher (?).

That being said the short array syntax introduced in 5.4 could make the code nicer: http://docs.php.net/manual/en/migration54.new-features.php
In 5.5 I don't see anything that would be good for us: http://docs.php.net/manual/en/migration55.new-features.php

**Comment by jamescun** [comment]
PHP version usage (linked from http://php.net/usage.php) http://w3techs.com/technologies/details/pl-php/5/all

**Comment by GrahamCampbell** [comment]
> PHP version usage (linked from http://php.net/usage.php) http://w3techs.com/technologies/details/pl-php/5/all

That data is pretty inaccurate. A better source to look for people actually using composer would be http://seld.be/notes/php-versions-stats-2015-edition.

**Comment by GrahamCampbell** [comment]
![image](https://cloud.githubusercontent.com/assets/2829600/12304216/54225030-ba26-11e5-9f34-3f339d6622ab.png)

**Comment by GrahamCampbell** [comment]
> I'm a bit reluctant to bump the minimum requirement because people never update their PHP. I don't think that it's our role to force people to upgrade to use Pusher (?).

TBH, I agree that it's in pusher's interest to keep php 5.3 support for now, and bump to 5.5 for the next major release.

**Comment by zimbatm** [comment]
Ok I'm making a call to keep 5.3 compatibility for now. Also because I think that people would benefit from upgrading to the new-lib once it's released. It was a good discussion to have still.

**Comment by vinkla** [comment]
I agree with @GrahamCampbell, the next major bump we should target 5.5 instead of 5.3.
